sonar.projectKey=rafseggom_Watchbug_TFG
sonar.organization=rafseggom


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=Watchbug_TFG
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Configuración del motor de análisis
sonar.python.version=3.10
sonar.sourceEncoding=UTF-8

# Ubicación del código fuente y tests
# Definimos 'watchbug' como la fuente principal para que Sonar no analice la raíz completa
sonar.sources=watchbug
sonar.tests=tests
sonar.test.inclusions=tests/**/test_*.py

# Cobertura de código (Crucial para el TFG)
# Esto vincula los resultados de pytest-cov con el panel de SonarCloud
sonar.python.coverage.reportPaths=coverage.xml

# Exclusiones de análisis
# Evitamos que Sonar analice ejemplos, scripts de configuración o archivos generados
sonar.exclusions=examples/**, setup.py, setup_supabase.py, **/__init__.py, .github/scripts/**

# Calidad y duplicación
# Ignoramos duplicaciones en los tests, ya que es normal repetir estructuras allí[cite: 1]
sonar.cpd.exclusions=tests/**